gazebo_ros_control/pid_gains:
    panda_joint1: {p: 12000, i: 0.0, d: 50, i_clamp: 10000}        
    panda_joint2: {p: 30000, i: 0.02, d: 100, i_clamp: 10000}        
    panda_joint3: {p: 18000, i: 0.01, d: 50, i_clamp: 1}        
    panda_joint4: {p: 18000, i: 0.01, d: 70, i_clamp: 10000}        
    panda_joint5: {p: 12000, i: 0.01, d: 70, i_clamp: 1}        
    panda_joint6: {p: 7000, i: 0.01, d: 50, i_clamp: 1}        
    panda_joint7: {p: 2000, i: 0.0, d: 20, i_clamp: 1}    
    panda_finger_joint1: { p: 10000, d: 30.0, i: 0.01, i_clamp: 1 }
    panda_finger_joint2: { p: 10000, d: 30.0, i: 0.01, i_clamp: 1 }        
